### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by trackedsupport** [blueimp/jQuery-File-Upload#3704]
I have someone that is getting a strange error. I haven't had anyone else run into this issue. Does anyone know what is causing it? Im storing files in localdb with dexie and then upload them with this. Im using Ruby on Rails 6.1 with webpacker. 

One other thing is they said they are getting these. Maybe its some setting with their Chrome browser?
![Screen Shot 2021-01-12 at 22 15 26](https://user-images.githubusercontent.com/29817223/104396613-00268580-5519-11eb-86e7-c72e514fc0b9.png)
![Screen Shot 2021-01-12 at 22 15 34](https://user-images.githubusercontent.com/29817223/104396615-0288df80-5519-11eb-8e8d-c9ffaea2be82.png)
![Screen Shot 2021-01-12 at 22 15 43](https://user-images.githubusercontent.com/29817223/104396622-0452a300-5519-11eb-9a84-723ba26cda6c.png)

```
VM21:294 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at HTMLDocument.document.createElement (<anonymous>:294:15)
    at HTMLDocument.document.createElement (<anonymous>:292:44)
    at HTMLDocument.document.createElement (<anonymous>:292:44)
    at $.<computed>.<computed>._initTemplates (eval at e.exports (addScript.js:20), <anonymous>:617:53)
    at $.<computed>.<computed>.eval [as _initTemplates] (eval at e.exports (addScript.js:20), <anonymous>:151:31)
    at $.<computed>.<computed>._initSpecialOptions (eval at e.exports (addScript.js:20), <anonymous>:643:12)
    at $.<computed>.<computed>.eval [as _initSpecialOptions] (eval at e.exports (addScript.js:20), <anonymous>:151:31)
    at $.<computed>.<computed>._create (eval at e.exports (addScript.js:20), <anonymous>:1413:12)
    at $.<computed>.<computed>.eval [as _create] (eval at e.exports (addScript.js:20), <anonymous>:151:31)
    at $.<computed>.<computed>._super (eval at e.exports (addScript.js:20), <anonymous>:138:39)
rollbar.min.js:1 jQuery.Deferred exception: Cannot read property 'then' of undefined TypeError: Cannot read property 'then' of undefined
    at File.eval (eval at e.exports (https://app.iris.fm/packs/js/application-afe787b75da0b5eb5dec.js:2:5763), <anonymous>:144:56)
    at Function.each (https://app.iris.fm/packs/js/application-afe787b75da0b5eb5dec.js:2:3391)
    at $.<computed>.<computed>.process (eval at e.exports (https://app.iris.fm/packs/js/application-afe787b75da0b5eb5dec.js:2:5763), <anonymous>:131:11)
    at $.<computed>.<computed>.eval [as process] (eval at e.exports (https://app.iris.fm/packs/js/application-afe787b75da0b5eb5dec.js:2:5763), <anonymous>:151:31)
    at HTMLInputElement.eval (eval at e.exports (https://app.iris.fm/packs/js/application-afe787b75da0b5eb5dec.js:2:5763), <anonymous>:248:45)
    at Function.each (https://app.iris.fm/packs/js/application-afe787b75da0b5eb5dec.js:2:3391)
    at e.fn.init.each (https://app.iris.fm/packs/js/application-afe787b75da0b5eb5dec.js:2:1865)
    at e.fn.init.$.fn.<computed> [as fileupload] (eval at e.exports (https://app.iris.fm/packs/js/application-afe787b75da0b5eb5dec.js:2:5763), <anonymous>:231:16)
    at $.<computed>.<computed>.eval (eval at e.exports (https://app.iris.fm/packs/js/application-afe787b75da0b5eb5dec.js:2:5763), <anonymous>:92:24)
    at f (https://app.iris.fm/packs/js/application-afe787b75da0b5eb5dec.js:2:17738) undefined
e.<computed> @ rollbar.min.js:1
```

**Comment by blueimp** [comment]
Please see #2190
